### PR TITLE
I made your code look better, you're welcome

### PR DESCRIPTION
**Pull request by Jankoy**
!!!

### CODE REVIEW

**Review by CyrusTheDragon — COMMENTED** [review]
I will not be accepting this pull request as i'd like to keep the original even if it doesnt look great

**Comment by Jankoy** [comment]
Good job, you passed my test.

**Comment by Jankoy** [comment]
I was trying to teach you about keeping consistency in your projects and not letting people just walk in and use their own style for things.

**Comment by CyrusTheDragon** [comment]
hm..

**Pull request closed without merging**
